import { useState, useEffect } from 'react';
import { BarChart3, PieChart, TrendingUp, Download, FileText, Calendar, Filter, Share2, Loader2, X, Check } from 'lucide-react';
import { db } from '../lib/firebase';
import { collection, getDocs } from 'firebase/firestore';
import clsx from 'clsx';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ReportsPage() {
  const [reportType, setReportType] = useState<'financial' | 'gst' | 'audit'>('financial');
  const [loading, setLoading] = useState(true);
  const [metrics, setMetrics] = useState({
    netSales: 0,
    gstLiability: 0,
    totalPurchases: 0
  });

  const [fiscalYear, setFiscalYear] = useState('All Time');
  const [showYearMenu, setShowYearMenu] = useState(false);
  const [showConfig, setShowConfig] = useState(false);
  const [includeCancelled, setIncludeCancelled] = useState(false);
  const [comparePrevious, setComparePrevious] = useState(false);

  useEffect(() => {
    async function fetchMetrics() {
      if (!db) return;
      setLoading(true);
      try {
        // Fetch Invoices for Sales & GST
        const invoicesRef = collection(db, 'invoices');
        const invoicesSnap = await getDocs(invoicesRef);
        let sales = 0;
        let gst = 0;
        invoicesSnap.forEach(doc => {
          const data = doc.data();
          
          let includeDate = true;
          if (fiscalYear !== 'All Time' && data.date) {
            const dateObj = new Date(data.date);
            const year = dateObj.getFullYear();
            const month = dateObj.getMonth();
            const docFY = month >= 3 ? `${year}-${year+1}` : `${year-1}-${year}`;
            if (docFY !== fiscalYear) includeDate = false;
          }

          if ((data.status !== 'cancelled' || includeCancelled) && includeDate) {
            sales += data.subtotal || 0;
            gst += data.tax_total || 0;
          }
        });

        // Fetch Purchases
        const purchasesRef = collection(db, 'purchases');
        const purchasesSnap = await getDocs(purchasesRef);
        let purchases = 0;
        purchasesSnap.forEach(doc => {
          const data = doc.data();

          let includeDate = true;
          if (fiscalYear !== 'All Time' && data.date) {
            const dateObj = new Date(data.date);
            const year = dateObj.getFullYear();
            const month = dateObj.getMonth();
            const docFY = month >= 3 ? `${year}-${year+1}` : `${year-1}-${year}`;
            if (docFY !== fiscalYear) includeDate = false;
          }

          if (includeDate) {
            purchases += data.grandTotal || data.amount || 0;
          }
        });

        setMetrics({
          netSales: sales,
          gstLiability: gst,
          totalPurchases: purchases
        });
      } catch (err) {
        console.error('Error fetching report metrics:', err);
      } finally {
        setLoading(false);
      }
    }

    fetchMetrics();
  }, [fiscalYear, includeCancelled]);

  const stats = [
    { label: 'Net Sales', value: `₹ ${metrics.netSales.toLocaleString()}`, change: '+12%', icon: TrendingUp, color: 'text-success' },
    { label: 'GST Liability', value: `₹ ${metrics.gstLiability.toLocaleString()}`, change: '+5%', icon: PieChart, color: 'text-primary' },
    { label: 'Total Purchases', value: `₹ ${metrics.totalPurchases.toLocaleString()}`, change: '-2%', icon: BarChart3, color: 'text-warning' },
  ];

  const handleDownloadGSTR1 = async () => {
    if (!db) return;
    try {
      const invoicesRef = collection(db, 'invoices');
      const invoicesSnap = await getDocs(invoicesRef);
      const data: any[] = [];
      invoicesSnap.forEach(doc => {
        const inv = doc.data();
        if (inv.status !== 'cancelled') {
          data.push({
            'Invoice Number': inv.invoice_number || '',
            'Invoice Date': inv.date || '',
            'Customer Name': inv.customer_name || '',
            'GSTIN': inv.customer_gstin || '',
            'Taxable Value': inv.subtotal || 0,
            'Total Tax': inv.tax_total || 0,
            'Total Invoice Value': inv.grandTotal || (inv.subtotal + (inv.tax_total || 0)) || 0
          });
        }
      });
      
      const ws = XLSX.utils.json_to_sheet(data);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "GSTR-1");
      XLSX.writeFile(wb, "Monthly_GSTR-1.xlsx");
    } catch (error) {
      console.error('Error generating GSTR-1', error);
      alert('Failed to generate GSTR-1');
    }
  };

  const handleDownloadIncomeStatement = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("Income Statement", 14, 22);
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text("Generated by Financial Intelligence", 14, 30);
    
    autoTable(doc, {
      startY: 40,
      head: [['Category', 'Amount (INR)']],
      body: [
        ['Net Sales Revenue', `Rs. ${metrics.netSales.toLocaleString()}`],
        ['Total Purchases / Expenses', `Rs. ${metrics.totalPurchases.toLocaleString()}`],
        ['Gross Margin', `Rs. ${(metrics.netSales - metrics.totalPurchases).toLocaleString()}`],
        ['GST Liability', `Rs. ${metrics.gstLiability.toLocaleString()}`],
      ],
      theme: 'striped',
    });
    
    doc.save("Income_Statement.pdf");
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight text-primary-dark uppercase italic">Financial Intelligence</h1>
          <p className="text-secondary mt-1 font-medium bg-primary/5 px-3 py-1 rounded-lg inline-block">Real-time fiscal monitoring enabled.</p>
        </div>
        <div className="flex gap-3">
          <button onClick={handleDownloadGSTR1} className="neo-btn flex items-center gap-2 group">
            <Share2 size={18} className="group-hover:text-primary transition-colors" />
            <span className="hidden sm:inline">Export Data</span>
          </button>
          <button onClick={handleDownloadIncomeStatement} className="neo-btn-primary flex items-center gap-2 shadow-neo-raised hover:translate-y-[-2px] transition-transform">
            <Download size={18} />
            <span className="hidden sm:inline">Download PDF</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {stats.map((stat) => (
          <div key={stat.label} className="neo-card flex flex-col justify-between h-32 group hover:shadow-neo-inset transition-all cursor-default overflow-hidden relative">
            {loading && (
              <div className="absolute inset-0 bg-surface/50 backdrop-blur-[2px] z-10 flex items-center justify-center">
                <Loader2 className="animate-spin text-primary" size={24} />
              </div>
            )}
            <div className="flex justify-between items-start">
               <span className="text-secondary font-bold text-xs uppercase tracking-widest leading-tight">{stat.label}</span>
               <stat.icon size={18} className="text-secondary opacity-30 group-hover:opacity-100 transition-opacity" />
            </div>
            <div className="flex items-baseline gap-2">
               <span className="text-3xl font-black text-primary-dark tracking-tight">{stat.value}</span>
               {!loading && <span className={`text-[10px] font-black uppercase ${stat.color}`}>{stat.change}</span>}
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 mt-8">
        {/* Report Selection Sidebar */}
        <div className="space-y-4">
           {['financial', 'gst', 'audit'].map((type) => (
              <button 
                key={type}
                onClick={() => setReportType(type as any)}
                className={`w-full text-left p-4 neo-card flex items-center gap-3 transition-all ${
                   reportType === type ? 'bg-primary/5 border-l-4 border-primary shadow-neo-pressed' : 'hover:bg-shadow-darker/5'
                }`}
              >
                 {type === 'financial' && <TrendingUp size={18} className={reportType === type ? 'text-primary' : 'text-secondary'} />}
                 {type === 'gst' && <PieChart size={18} className={reportType === type ? 'text-primary' : 'text-secondary'} />}
                 {type === 'audit' && <Shield size={18} className={reportType === type ? 'text-primary' : 'text-secondary'} />}
                 <span className={`font-black uppercase tracking-tighter text-xs ${reportType === type ? 'text-primary-dark' : 'text-secondary'}`}>
                    {type} Statements
                 </span>
              </button>
           ))}
        </div>

        {/* Report Preview / Details */}
        <div className="lg:col-span-3 space-y-6">
           <div className="neo-card min-h-[400px] flex flex-col">
              <div className="flex justify-between items-center mb-6">
                 <h3 className="flex items-center gap-2 text-primary-dark uppercase font-black">
                    {reportType.toUpperCase()} SUMMARY {fiscalYear !== 'All Time' ? `(FY ${fiscalYear})` : '(ALL TIME)'}
                 </h3>
                  <div className="flex gap-2 relative">
                     <button onClick={() => setShowYearMenu(!showYearMenu)} className="neo-btn !py-1.5 !px-3 text-xs flex items-center gap-1 hover:bg-primary/5 transition-colors">
                        <Calendar size={14} />
                        {fiscalYear === 'All Time' ? 'Fiscal Year' : `FY ${fiscalYear}`}
                     </button>
                     
                     {showYearMenu && (
                        <div className="absolute top-10 left-0 w-36 bg-surface shadow-neo-raised rounded-lg border border-shadow-darker/10 p-2 z-20 animate-fade-in">
                           {['All Time', '2025-2026', '2026-2027'].map((fy) => (
                             <button
                               key={fy}
                               onClick={() => { setFiscalYear(fy); setShowYearMenu(false); }}
                               className={`w-full text-left px-3 py-2 text-xs rounded-md flex items-center justify-between ${fiscalYear === fy ? 'bg-primary/10 text-primary-dark font-bold' : 'hover:bg-shadow-darker/5 text-secondary transition-colors'}`}
                             >
                               {fy}
                               {fiscalYear === fy && <Check size={12} className="text-primary" />}
                             </button>
                           ))}
                        </div>
                     )}

                     <button onClick={() => setShowConfig(true)} className="neo-btn !py-1.5 !px-3 text-xs flex items-center gap-1 hover:bg-primary/5 transition-colors">
                        <Filter size={14} />
                        Configure
                     </button>
                  </div>
              </div>

              {loading ? (
                <div className="flex-1 flex flex-col justify-center items-center text-center p-8 bg-shadow-darker/5 rounded-xl border border-shadow-darker/10">
                   <div className="w-16 h-16 rounded-full bg-surface shadow-neo-raised flex items-center justify-center text-secondary mb-4 opacity-50">
                      <Loader2 size={32} className="animate-spin text-primary" />
                   </div>
                   <h4 className="text-primary-dark font-bold">Calculating Real-time data...</h4>
                   <p className="text-secondary text-sm mt-1 max-w-xs">
                      Aggregate financial data from Firestore is being calculated for the report.
                   </p>
                   <div className="w-full max-w-md bg-shadow-darker/10 h-1.5 rounded-full mt-6 overflow-hidden">
                      <div className="bg-primary h-full transition-all duration-1000 w-1/3 animate-pulse"></div>
                   </div>
                </div>
              ) : (
                <div className="flex-1 p-6 bg-surface rounded-xl border border-shadow-darker/10 shadow-neo-inset">
                  {reportType === 'financial' && (
                    <div className="space-y-4 animate-fade-in">
                      <div className="flex justify-between items-center p-4 bg-shadow-darker/5 rounded-lg">
                        <span className="text-secondary font-semibold">Gross Sales Revenue</span>
                        <span className="text-lg font-black text-primary-dark">₹ {metrics.netSales.toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between items-center p-4 bg-shadow-darker/5 rounded-lg">
                        <span className="text-secondary font-semibold">Total Purchases / Expenses</span>
                        <span className="text-lg font-black text-warning">₹ {metrics.totalPurchases.toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between items-center p-4 bg-primary/10 rounded-lg border border-primary/20">
                        <span className="text-primary-dark font-bold">Gross Margin</span>
                        <span className="text-xl font-black text-primary">₹ {(metrics.netSales - metrics.totalPurchases).toLocaleString()}</span>
                      </div>
                    </div>
                  )}
                  {reportType === 'gst' && (
                    <div className="space-y-4 animate-fade-in">
                      <div className="flex justify-between items-center p-4 bg-shadow-darker/5 rounded-lg">
                        <span className="text-secondary font-semibold">Total Taxable Value (Sales)</span>
                        <span className="text-lg font-black text-primary-dark">₹ {metrics.netSales.toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between items-center p-4 bg-shadow-darker/5 rounded-lg">
                        <span className="text-secondary font-semibold">Estimated CGST</span>
                        <span className="text-lg font-black text-secondary">₹ {(metrics.gstLiability / 2).toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between items-center p-4 bg-shadow-darker/5 rounded-lg">
                        <span className="text-secondary font-semibold">Estimated SGST</span>
                        <span className="text-lg font-black text-secondary">₹ {(metrics.gstLiability / 2).toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between items-center p-4 bg-primary/10 rounded-lg border border-primary/20">
                        <span className="text-primary-dark font-bold">Total Output Tax Liability</span>
                        <span className="text-xl font-black text-primary">₹ {metrics.gstLiability.toLocaleString()}</span>
                      </div>
                    </div>
                  )}
                  {reportType === 'audit' && (
                    <div className="flex flex-col items-center justify-center py-12 opacity-50 animate-fade-in">
                      <Shield size={48} className="text-secondary mb-4" />
                      <p className="text-secondary font-medium">Audit logs are currently empty for this period.</p>
                    </div>
                  )}
                </div>
              )}
           </div>

           <div className="neo-card space-y-4">
              <h4 className="text-xs font-black text-secondary tracking-widest uppercase">Available Downloads</h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                 <button onClick={handleDownloadGSTR1} className="neo-btn p-4 flex items-center justify-between group">
                    <div className="flex items-center gap-3">
                       <FileText size={20} className="text-error" />
                       <span className="text-sm font-bold text-primary-dark text-left">Monthly GSTR-1 (XLS)</span>
                    </div>
                    <Download size={14} className="opacity-0 group-hover:opacity-100 transition-opacity" />
                 </button>
                 <button onClick={handleDownloadIncomeStatement} className="neo-btn p-4 flex items-center justify-between group">
                    <div className="flex items-center gap-3">
                       <FileText size={20} className="text-primary" />
                       <span className="text-sm font-bold text-primary-dark text-left">Income Statement (PDF)</span>
                    </div>
                    <Download size={14} className="opacity-0 group-hover:opacity-100 transition-opacity" />
                 </button>
              </div>
           </div>
        </div>
      </div>

      {showConfig && (
        <div className="fixed inset-0 bg-shadow-darker/20 backdrop-blur-sm flex items-center justify-center z-50 animate-fade-in">
          <div className="bg-surface rounded-2xl shadow-neo-raised w-full max-w-md p-6 border border-shadow-darker/10">
             <div className="flex justify-between items-center mb-6">
                <h3 className="text-xl font-bold text-primary-dark tracking-tight">Report Configuration</h3>
                <button onClick={() => setShowConfig(false)} className="p-2 hover:bg-shadow-darker/5 rounded-full transition-colors text-secondary">
                  <X size={20} />
                </button>
             </div>
             
             <div className="space-y-6">
                <div className="flex items-center justify-between p-4 neo-card bg-shadow-darker/5">
                   <div>
                      <h4 className="font-semibold text-primary-dark">Include Cancelled Invoices</h4>
                      <p className="text-xs text-secondary mt-1">Calculate gross values including voided transactions</p>
                   </div>
                   <button 
                     onClick={() => setIncludeCancelled(!includeCancelled)}
                     className={`w-12 h-6 rounded-full transition-colors relative ${includeCancelled ? 'bg-primary' : 'bg-shadow-darker/20'}`}
                   >
                     <div className={`w-4 h-4 bg-surface rounded-full absolute top-1 transition-all ${includeCancelled ? 'left-7' : 'left-1 shadow-sm'}`}></div>
                   </button>
                </div>
                
                <div className="flex items-center justify-between p-4 neo-card bg-shadow-darker/5">
                   <div>
                      <h4 className="font-semibold text-primary-dark">Compare to Previous Year</h4>
                      <p className="text-xs text-secondary mt-1">Show % change against previous fiscal period</p>
                   </div>
                   <button 
                     onClick={() => setComparePrevious(!comparePrevious)}
                     className={`w-12 h-6 rounded-full transition-colors relative ${comparePrevious ? 'bg-primary' : 'bg-shadow-darker/20'}`}
                   >
                     <div className={`w-4 h-4 bg-surface rounded-full absolute top-1 transition-all ${comparePrevious ? 'left-7' : 'left-1 shadow-sm'}`}></div>
                   </button>
                </div>
             </div>

             <div className="mt-8 flex justify-end">
                <button onClick={() => setShowConfig(false)} className="neo-btn-primary px-6 py-2">
                   Apply Configuration
                </button>
             </div>
          </div>
        </div>
      )}
    </div>
  );
}

function Shield({ size, className }: { size: number, className?: string }) {
  return (
    <svg 
      width={size} 
      height={size} 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2" 
      strokeLinecap="round" 
      strokeLinejoin="round" 
      className={className}
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10" />
    </svg>
  );
}
