import { onCall, HttpsError } from "firebase-functions/v2/https";
import { onSchedule } from "firebase-functions/v2/scheduler";
import { defineSecret } from "firebase-functions/params";
import { GoogleGenAI } from "@google/genai";
import { db } from "../config.js";
import { executeTool } from "./tools.js";
import { FieldValue } from "firebase-admin/firestore";
const googleGenAiApiKey = defineSecret("GOOGLE_GENAI_API_KEY");
// Budget Constraints
const GOOGLE_CREDIT_CEILING = 1500.00;
const BUFFER_THRESHOLD = 0.95;
function calculateCreditCost(usage, cachedPromptTokens = 0) {
    const INPUT_COST_PER_TOKEN = 0.000000075;
    const CACHED_INPUT_COST_PER_TOKEN = 0.00000001875;
    const OUTPUT_COST_PER_TOKEN = 0.00000030;
    const regularInputTokens = Math.max(0, usage.promptTokens - cachedPromptTokens);
    return (regularInputTokens * INPUT_COST_PER_TOKEN) +
        (cachedPromptTokens * CACHED_INPUT_COST_PER_TOKEN) +
        (usage.candidatesTokens * OUTPUT_COST_PER_TOKEN);
}
/**
 * AI Tool Gateway
 * Intercepts tool calls generated by the AI (via the frontend),
 * authenticates the user, checks roles, and executes the underlying business logic safely.
 */
export const aiToolGateway = onCall({ cors: true }, async (request) => {
    if (!request.auth) {
        throw new HttpsError("unauthenticated", "You must be logged in to use AI tools.");
    }
    const uid = request.auth.uid;
    const { toolName, args } = request.data;
    if (!toolName) {
        throw new HttpsError("invalid-argument", "Missing toolName in request.");
    }
    // 1. Authenticate & Get Role from Database
    const userDoc = await db.collection("users").doc(uid).get();
    if (!userDoc.exists) {
        throw new HttpsError("permission-denied", "User record not found.");
    }
    const userData = userDoc.data();
    if (userData?.is_active === false) {
        throw new HttpsError("permission-denied", "User account is disabled.");
    }
    const userRole = userData?.role;
    if (!['admin', 'accounts', 'sales'].includes(userRole)) {
        throw new HttpsError("permission-denied", "Invalid user role.");
    }
    const context = {
        uid,
        role: userRole,
        userName: userData?.name || 'Unknown'
    };
    try {
        // 2. Route & Execute Tool securely
        const result = await executeTool(toolName, args || {}, context);
        // 3. System Audit Log for all AI Gateway interactions
        await db.collection("audit_logs").add({
            document_type: "ai_action",
            action: toolName,
            user_id: uid,
            timestamp: new Date(),
            notes: `AI executed ${toolName}`,
            source: "ai_agent",
            status: "success",
            arguments: args || {}
        });
        return { success: true, result };
    }
    catch (error) {
        console.error(`AI Gateway Error [${toolName}]:`, error);
        await db.collection("audit_logs").add({
            document_type: "ai_action",
            action: toolName,
            user_id: uid,
            timestamp: new Date(),
            notes: `AI execution failed: ${error.message}`,
            source: "ai_agent",
            status: "failed",
            arguments: args || {}
        });
        throw new HttpsError(error.code && error.code.startsWith("functions/") ? error.code.replace("functions/", "") : "internal", error.message || "Failed to execute AI tool");
    }
});
/**
 * Ephemeral Token Generator for Gemini Live API
 * Securely contacts Google GenAI to create a short-lived token for the browser connection.
 */
export const getGeminiLiveEphemeralToken = onCall({ cors: true, secrets: [googleGenAiApiKey] }, async (request) => {
    if (!request.auth) {
        throw new HttpsError("unauthenticated", "You must be logged in to access AI features.");
    }
    try {
        console.log("[GEMINI_DIAGNOSTICS] getGeminiLiveEphemeralToken START");
        const apiKey = googleGenAiApiKey.value() || process.env.GOOGLE_GENAI_API_KEY;
        if (!apiKey) {
            console.error("[GEMINI_DIAGNOSTICS] getGeminiLiveEphemeralToken FAILED: API key missing");
            throw new Error("GOOGLE_GENAI_API_KEY is not configured.");
        }
        const ai = new GoogleGenAI({ apiKey: apiKey });
        console.log("[GEMINI_DIAGNOSTICS] Requesting ephemeral token for gemini-3.8-live");
        const response = await ai.authTokens.create({
            liveConnectConstraints: {
                model: "models/gemini-3.8-live",
                responseModalities: ["AUDIO"]
            }
        });
        console.log("[GEMINI_DIAGNOSTICS] getGeminiLiveEphemeralToken SUCCESS: Token generated", response.name);
        // The browser connects using this temporary token 'name'
        return {
            token: response.name, // response.name acts as the token value in this API
            url: "wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContentConstrained"
        };
    }
    catch (error) {
        console.error("[GEMINI_DIAGNOSTICS] getGeminiLiveEphemeralToken FAILED: Exception thrown", error);
        console.error("Error generating Gemini token:", error);
        throw new HttpsError("internal", error.message || "Failed to generate token");
    }
});
/**
 * Main Executable Middleware Wrapper for all Bill Pro Agent onBlur Actions
 */
export const executeBillProAgentTask = onCall({ cors: true, secrets: [googleGenAiApiKey] }, async (request) => {
    if (!request.auth)
        throw new HttpsError("unauthenticated", "Must be logged in.");
    const { promptPayload, options = {} } = request.data;
    const organizationId = request.auth.uid; // Mocking orgId via user uid for now
    const budgetRef = db.collection('system_config').doc('gemini_budget');
    // 1. Enforce Circuit Breaker
    const budgetSnap = await budgetRef.get();
    let totalCreditsConsumed = 0;
    if (budgetSnap.exists) {
        totalCreditsConsumed = budgetSnap.data()?.creditsUsed || 0;
    }
    if (totalCreditsConsumed >= GOOGLE_CREDIT_CEILING) {
        console.error(`🚨 AI Budget Blocked: 1500 Credit Ceiling reached (${totalCreditsConsumed.toFixed(2)} used).`);
        return {
            success: false,
            fallbackActive: true,
            text: JSON.stringify({
                status: "ERROR",
                severity: "HIGH",
                avatarState: "warning",
                voiceAlertText: "Budget constraint active. Running structural offline rule validations instead."
            })
        };
    }
    try {
        const apiKey = googleGenAiApiKey.value() || process.env.GOOGLE_GENAI_API_KEY;
        const ai = new GoogleGenAI({ apiKey: apiKey });
        const SYSTEM_INSTRUCTION = `
## MODULE 1: CORE AGENT PERSONALITY
You are an elite, real-time autonomous AI Assistant ("Master Worker") built directly inside the 'Bill Pro' web app ecosystem. Your communication style is helpful, direct, and encouraging. Only output valid JSON matching the system schema.
CRITICAL: You should reply in English by default. However, if the user speaks to you in Tamil or Tanglish, you may respond in Tanglish (Tamil written in English) or Tamil. Match the user's language.

## MODULE 2: APP NAVIGATION AND DATA ENTRY
You can perform actions based on user requests. If the user asks to go somewhere, use "NAVIGATE". If they want to add a product or customer, use "ADD_PRODUCT" or "ADD_CUSTOMER". 
If they want to create an invoice, quotation, cash memo, or proforma, use "PREFILL_DOCUMENT".

Valid routes for NAVIGATE:
- /dashboard
- /invoices
- /invoices/new
- /quotations
- /quotations/new
- /products
- /customers
- /settings

Respond STRICTLY in this JSON format:
{
  "action": "NAVIGATE" | "ADD_PRODUCT" | "ADD_CUSTOMER" | "PREFILL_DOCUMENT" | "REPLY",
  "target": "/route_path" (or "/quotations/new", "/invoices/new" for PREFILL_DOCUMENT),
  "payload": { 
      "name": "Item Name", "retail_price": 100, "phone": "1234567890",
      "customerSearch": "John Doe", 
      "items": [{ "productSearch": "Trophy", "quantity": 5 }]
  },
  "status": "SUCCESS" | "ERROR",
  "severity": "LOW" | "MEDIUM" | "HIGH",
  "avatarState": "thinking" | "warning" | "idle" | "celebrating",
  "message": "Your conversational response here in Tanglish or Tamil. Be helpful and direct."
}
`;
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: promptPayload,
            config: {
                systemInstruction: SYSTEM_INSTRUCTION,
                responseMimeType: "application/json"
            }
        });
        // 3. Extract exact token metadata
        const metadata = response.usageMetadata;
        const usageMetrics = {
            promptTokens: metadata?.promptTokenCount || 0,
            candidatesTokens: metadata?.candidatesTokenCount || 0,
            totalTokens: metadata?.totalTokenCount || 0
        };
        const cachedTokens = metadata?.cachedContentTokenCount || 0;
        // 4. Transform token weights into credit numbers
        const runtimeTransactionCost = calculateCreditCost(usageMetrics, cachedTokens);
        // 5. Atomic transaction log up-count
        await db.runTransaction(async (transaction) => {
            transaction.set(budgetRef, {
                creditsUsed: FieldValue.increment(runtimeTransactionCost),
                lastUpdated: FieldValue.serverTimestamp()
            }, { merge: true });
            const auditLogsRef = db.collection('organizations').doc(organizationId).collection('ai_token_logs').doc();
            transaction.set(auditLogsRef, {
                timestamp: FieldValue.serverTimestamp(),
                tokensConsumed: usageMetrics.totalTokens,
                cachedTokensApplied: cachedTokens,
                transactionCostCredits: runtimeTransactionCost
            });
        });
        const projectedNewTotal = totalCreditsConsumed + runtimeTransactionCost;
        const isApproachingCeiling = projectedNewTotal >= (GOOGLE_CREDIT_CEILING * BUFFER_THRESHOLD);
        return {
            success: true,
            fallbackActive: false,
            text: response.text,
            budgetAlert: isApproachingCeiling ? "WARNING: Agent operation budget running low." : null
        };
    }
    catch (error) {
        console.error("Critical connection failure within the Gemini Middleware:", error);
        throw new HttpsError("internal", error.message || "Pipeline failed");
    }
});
//# sourceMappingURL=gateway.js.map