import { onCall, HttpsError } from "firebase-functions/v2/https";
import { defineSecret } from "firebase-functions/params";
import { GoogleGenAI } from "@google/genai";
import { db } from "../config.js";
import { executeTool } from "./tools.js";
const googleGenAiApiKey = defineSecret("GOOGLE_GENAI_API_KEY");
/**
 * AI Tool Gateway
 * Intercepts tool calls generated by the AI (via the frontend),
 * authenticates the user, checks roles, and executes the underlying business logic safely.
 */
export const aiToolGateway = onCall({ cors: true }, async (request) => {
    if (!request.auth) {
        throw new HttpsError("unauthenticated", "You must be logged in to use AI tools.");
    }
    const uid = request.auth.uid;
    const { toolName, args } = request.data;
    if (!toolName) {
        throw new HttpsError("invalid-argument", "Missing toolName in request.");
    }
    // 1. Authenticate & Get Role from Database
    const userDoc = await db.collection("users").doc(uid).get();
    if (!userDoc.exists) {
        throw new HttpsError("permission-denied", "User record not found.");
    }
    const userData = userDoc.data();
    if (userData?.is_active === false) {
        throw new HttpsError("permission-denied", "User account is disabled.");
    }
    const userRole = userData?.role;
    if (!['admin', 'accounts', 'sales'].includes(userRole)) {
        throw new HttpsError("permission-denied", "Invalid user role.");
    }
    const context = {
        uid,
        role: userRole,
        userName: userData?.name || 'Unknown'
    };
    try {
        // 2. Route & Execute Tool securely
        const result = await executeTool(toolName, args || {}, context);
        // 3. System Audit Log for all AI Gateway interactions
        await db.collection("audit_logs").add({
            document_type: "ai_action",
            action: toolName,
            user_id: uid,
            timestamp: new Date(),
            notes: `AI executed ${toolName}`,
            source: "ai_agent",
            status: "success",
            arguments: args || {}
        });
        return { success: true, result };
    }
    catch (error) {
        console.error(`AI Gateway Error [${toolName}]:`, error);
        await db.collection("audit_logs").add({
            document_type: "ai_action",
            action: toolName,
            user_id: uid,
            timestamp: new Date(),
            notes: `AI execution failed: ${error.message}`,
            source: "ai_agent",
            status: "failed",
            arguments: args || {}
        });
        throw new HttpsError(error.code && error.code.startsWith("functions/") ? error.code.replace("functions/", "") : "internal", error.message || "Failed to execute AI tool");
    }
});
/**
 * Ephemeral Token Generator for Gemini Live API
 * Securely contacts Google GenAI to create a short-lived token for the browser connection.
 */
export const getGeminiLiveEphemeralToken = onCall({ cors: true, secrets: [googleGenAiApiKey] }, async (request) => {
    if (!request.auth) {
        throw new HttpsError("unauthenticated", "You must be logged in to access AI features.");
    }
    try {
        console.log("[GEMINI_DIAGNOSTICS] getGeminiLiveEphemeralToken START");
        const apiKey = googleGenAiApiKey.value() || process.env.GOOGLE_GENAI_API_KEY;
        if (!apiKey) {
            console.error("[GEMINI_DIAGNOSTICS] getGeminiLiveEphemeralToken FAILED: API key missing");
            throw new Error("GOOGLE_GENAI_API_KEY is not configured.");
        }
        const ai = new GoogleGenAI({ apiKey: apiKey });
        console.log("[GEMINI_DIAGNOSTICS] Requesting ephemeral token for gemini-3.8-live");
        const response = await ai.authTokens.create({
            liveConnectConstraints: {
                model: "models/gemini-3.8-live",
                responseModalities: ["AUDIO"]
            }
        });
        console.log("[GEMINI_DIAGNOSTICS] getGeminiLiveEphemeralToken SUCCESS: Token generated", response.name);
        // The browser connects using this temporary token 'name'
        return {
            token: response.name, // response.name acts as the token value in this API
            url: "wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContentConstrained"
        };
    }
    catch (error) {
        console.error("[GEMINI_DIAGNOSTICS] getGeminiLiveEphemeralToken FAILED: Exception thrown", error);
        console.error("Error generating Gemini token:", error);
        throw new HttpsError("internal", error.message || "Failed to generate token");
    }
});
//# sourceMappingURL=gateway.js.map