/**
 * AI Tool Gateway
 * Intercepts tool calls generated by the AI (via the frontend),
 * authenticates the user, checks roles, and executes the underlying business logic safely.
 */
export declare const aiToolGateway: import("firebase-functions/v2/https").CallableFunction<any, Promise<{
    success: boolean;
    result: any;
}>, unknown>;
/**
 * Ephemeral Token Generator for Gemini Live API
 * Securely contacts Google GenAI to create a short-lived token for the browser connection.
 */
export declare const getGeminiLiveEphemeralToken: import("firebase-functions/v2/https").CallableFunction<any, Promise<{
    token: string | undefined;
    url: string;
}>, unknown>;
/**
 * Main Executable Middleware Wrapper for all Bill Pro Agent onBlur Actions
 */
export declare const executeBillProAgentTask: import("firebase-functions/v2/https").CallableFunction<any, Promise<{
    success: boolean;
    fallbackActive: boolean;
    text: string;
    budgetAlert?: never;
} | {
    success: boolean;
    fallbackActive: boolean;
    text: string | undefined;
    budgetAlert: string | null;
}>, unknown>;
//# sourceMappingURL=gateway.d.ts.map